### ISSUE TITLE
第二回アプリ製作 案出し 5回目 20220730

### ISSUE THREAD

**Issue by KanekoCadlab** [kurumu-rika/main#6]
宿題：各自↓のリーンキャンバスを作ってくる（宇佐美のコメントそのまま）

高齢者との会話補助アプリ
待ち合わせアプリ
資格のSNSアプリ
カフェの混み具合アプリ(宇佐美、今井持ち帰り)
思考整理用アプリ
クリエイターに優しいアプリ

前回のリーンキャンパス
https://github.com/kurumu-rika/yorimichi_application/issues/11

平野くんの作ってくれた
リーンキャンバスの[テンプレート](https://docs.google.com/spreadsheets/d/1KsRUUKRHeVPuMNb4rvoZ8HRJ8JqNngxTsASKP3ITxdM/edit?usp=sharing)

**Comment by KanekoCadlab** [comment]
# 広告収入について
- Androidアプリの広告収入は1ダウンロードあたり5円
（前に平野くんが調べてた気がする）
- ダウンロード数に応じた月額となる。（下記相場）
    - ビッグヒット(100万ダウンロード以上)で500万円
    - ミドルヒット(10万～50万ダウンロード)で20万～200万
    - スモールヒット(3万～5万ダウンロード)で５万円

[参考URL](https://crowdworks.jp/articles/6956/)

- SnapChatはもともとは広告収入が主な収入源だった。

**Comment by hirano0709** [comment]
@usamin24 @umatama @KanekoCadlab 
リーンキャンバスの項目の説明を[Wiki](https://github.com/kurumu-rika/main/wiki/%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%90%E3%82%B9%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9)にまとめました．
参考にしてください．
あと，yorimichiリポジトリにあった調べ物は，mainリポジトリのWikiに移動しました．
併せて確認お願いします．

**Comment by KanekoCadlab** [comment]
# アイデアを形にしていく上で気にしたいこと
（気づいたことがあれば追記してほしい）
- アイデアの重要な機能が実現可能か。コスト含む
- 開発期間や費用を考慮するとAI機能導入は初期構築では厳しい。2次開発以降で実施。条件さえ満たせば初期構築でも可。
- 広告費で実施できるサービスならニーズそっちのけでじゃんじゃん作っていいのでは？モチベ次第だけど。


usami
- そもそもチームとしてのアプリ開発の目的は？スキルアップ、副業、アプリ開発経験？それによってどこをどのくらいちゃんと考えるかが変わりそう(目的によってはビジネスモデルはちゃんとしなくて良さそう)
- ビジネスモデルを考えるのであれば、使用者の経済合理性、事業者の経済合理性が必須と本で読みました。こういうの描いてみるのもあり。3×3でいろんなビジネスモデルをまとめている ( https://bizgram.zukai.co/)
- スキルアップが一番の目的であれば、このアプリを開発することでどんな技術が身につくかという視点もあってよい
- どんなものを作るか、制約を明確化しておいたほうが良さそう (アプリだけで完結するものしか作れないのか、宅配とかサービスを含めたアプリを開発するときはどうするのか、あとは企業で使う業務システムは作れないのかとか)

**Comment by usamin24** [comment]
宿題提出します。

https://docs.google.com/spreadsheets/d/1HkU2nrajIYq7SpEZDYVC7bbx7jDSTWbD4ytrDqvZ8W4/edit?usp=sharing

**Comment by umatama** [comment]
宿題のリンク貼りつけつつ、宿題します

[リーンキャンパス_第二回アプリ製作_イマイ](https://docs.google.com/spreadsheets/d/1w3z8NrQBWgpJGmj8kp5qHaxGw-4nO-SpoYpmRf6U-qk/edit?usp=sharing)

[リンクトイン](https://directsourcing-lab.com/blog/about-linkedin/)

**Comment by KanekoCadlab** [comment]
宿題
[リーンキャンパス_第二回アプリ製作_カネコ](https://docs.google.com/spreadsheets/d/1bY4amivV_EjASqx2hc1lkxyK5vz-2FEeYHhiYXMmDrQ/edit#gid=1638517883)

**Comment by hirano0709** [comment]
宿題
[リーンキャンバス_平野](https://docs.google.com/spreadsheets/d/1XFLypav-53C8--lOJBzdvMobAasaMjZMeBs5Gd5y7w8/edit?usp=sharing)

**Comment by KanekoCadlab** [comment]
# アプリ開発の目的

チームとしての目的
  - 実際に使ってもらえるアプリ作成の経験

それぞれ個人の目的
- usami
  - スキルアップ（実装してテストするものを作るスキルアップ）
  - C+以外のアプリ開発、特にスマホアプリの知見を得たい

- imai
  - スキルアップ（自己研鑽。そこに明確な理由はない。スキル取得のプロセスを経験したい。）
  - 成果物をつくることがメインや 。趣味的な活動の1つ　繁忙期じゃないときに月20Hまでは趣味。

- hirano
  - 実際に使ってもらえるアプリ作成の経験
  - コーディングはおまけ。やればできる。

- kaneko
  -  広く使ってもらえる(みんなのスマホに入る、雑誌)知名度のあるアプリを作成
  -  地域特化にしたアプリいいね。

**Comment by KanekoCadlab** [comment]
# リーンキャンバスを踏まえてアイデアを絞る

- ~~高齢者との会話補助アプリ~~
- 待ち合わせアプリ（今井、平野）
リスク：そもそも待ち合わせに遅刻する人がいる根本の問題を解決できない
待ち合わせに遅刻する人がいるだけで起こすために電話～とかの手間が大きくかかるのは解決できない
Lineで予定や連絡を交換している現状に比べて、やることが多いのでハイコストローリターンに見える
GPS OFFにして寝てたら何もできない
GPS情報を共有するのはいつからか？とかプライバシーの問題もありそう
現状の組み合わせでできそうなので圧倒的な優位性がない
ビジネスモデルがわからない（広告出せない）
アプリの広め方が思いつかない
既存のアプリにないの？
→ビジネスモデルと、既存アプリの再調査。ソリューションの深堀

- 資格のSNSアプリ（今井、兼子）
リスク：既に資格を多くもっている人がこのアプリを使用するメリットが少ない
そこまで資格に多様性はないのではないか
アプリリリース初期に使用する人にメリットが少ない
個人情報の扱い
LinkedInとの差分がわからない
資格だけにしぼった場合の需要がないのでは
資格だけでなく、スキルとした場合にどうロードマップを作るのかわからない
→LinkedInをさわる。資格の種類とどうやって一覧を取得できるか調査

- カフェの混み具合アプリ(宇佐美、今井) 
  - 勉強できるとことかカフェだけでない発想もいい。お店側のメリットを考えるが、お店を絡ませると困難
  - 店側が混雑情報を提示する。いまないのはメリットがないから？
混んでいる、人気のカフェにメリットが大きい、不人気のカフェは意味あるのか？
客を待たせてでも入れたいという考え方もありそう
カフェ側に情報を掲載させてもらうのも許可が必要そう
ビジネスモデルがわからない
→ビジネスモデル。カフェ側とお客様側のメリットデメリットの抽出

- 思考整理用アプリ（兼子、宇佐美） 
  - 悩みに対して自分はこう考えて解決したというのを共有する
既存アプリもある程度使えそう
そこまでのニーズがなさそう、紙やPCの大きな画面のメリットが大きい
そもそも具体性がない
課題：外でPCや紙を持たずにアイデアを考える整理する手段がない
汎用的なツールでない思考整理用のアプリ（PCでも可）
→課題を絞ってソリューション書く。書いていない課題のリーンキャンバスを書く

- クリエイターに優しいアプリ（平野、兼子）
既存のSNSはいいねの数で人気の投稿をサジェストするようになっているが、いいねがなくなると何を基準にサジェストできるか
ソリューションが不明確
→ソリューションの具体化
クリエイターはつくったもの（技術や感性）を発表、認められたいから投稿する。フィードバックされたい。

**Comment by umatama** [comment]
- 資格のSNS　宇佐美、兼子
 初期のユーザをどう獲得するか
 linkedinとの圧倒的な差別化

- 思考整理用アプリ(汎用的なツール)　宇佐美
 チュートリアル用に作る？
 具体的な画面遷移などのイメージを説明できる感じの資料

- クリエイターに優しいアプリ(SDGs)　兼子、平野、今井
 ビジネスモデル
 費用再検討

- 前回の宿題　今井
 待ち合わせアプリ
