### ISSUE TITLE
洗い出したリスクに対する再調査・深掘り

### ISSUE THREAD

**Issue by hirano0709** [kurumu-rika/main#7]
[リーンキャンバスで洗い出したリスク](https://github.com/kurumu-rika/main/issues/6#issuecomment-1200088234)に対する再調査・深堀り等を行い，実際に手を付ける課題を選定する．
カッコ内は宿題の担当．
- 待ち合わせアプリ（今井，平野）
  - ビジネスモデルの具体化
  - 既存アプリの再調査
  - ソリューションの具体化
- 資格のSNSアプリ（今井，兼子）
  - LinkedInの使用感調査
  - あらゆる資格の種類の調査（その際どう調べたかも）
- カフェの混み具合アプリ（宇佐美，今井）
  - ビジネスモデルの具体化
  - カフェ側とお客様側のメリットデメリットの抽出
- 思考整理用アプリ（兼子，宇佐美）
  - 書いていない課題に対するリーンキャンバスの作成
- クリエイターに優しいアプリ（平野，兼子）
  - ソリューションの具体化

**Comment by hirano0709** [comment]
# 待ち合わせアプリ
## ソリューションの具体化
1. 待ち合わせアプリから，予定を作成する．（いつからいつまでGPSを共有するかも入力する）
1. Googleカレンダー等に予定を入れる．（API等を用いる）
1. 待ち合わせ相手にGPS共有承諾するかプッシュ通知を送信する．
1. 待ち合わせ相手が承諾すると，Googleレンダー等に予定を入れる．
1. 指定した待ち合わせ時間付近から，お互いのGPS情報が見れるようになる．
1. 明らかに間に合わないようなところにいる場合，通知を送信する．

## 既存アプリの再調査
既存アプリの概要，課金要素は以下の通りである．
ココイルは12時間限定でGPS共有ができる機能があるが，詳細な時間指定はできない．
それ以外については，時間の要素がないと思われる．（Zenly，Life360に関してはない．それ以外はおそらくない．）
| アプリ名 | 主なサブ機能 | 課金要素 |
| --- | --- | --- |
| Zenly | あいまいなGPS共有，目的地への経路表示 | なし |
| Life360 | 帰宅通知，緊急通知，バッテリー通知 | 行動レポート |
| ココイル | 12時間で消えるサークル | なし |
| iシェアリング | 接近通知，運転レポート | 行動レポート，広告表示なし |
| 家族用 Hachi | Apple Watch連携，ビデオ通話，SOS発信 | 見守る人数によって課金 |
| Find My Kids | 子供のアプリ利用状況確認 | 子供の活動履歴 |
| ココダヨ | 災害警報連携 | 家族の人数によって課金 |

## ビジネスモデルの具体化
考えられるユーザへの課金要素に対して，待ち合わせアプリが課金できるかどうか検討した．
- **行動レポート**
友人間では行動レポートが必要ない．
夫婦間，家族間，恋人間以外では行動レポートで課金できそうにない．
しかしそれらをターゲットにした待ち合わせアプリは，ニーズが少ないと思われる．（少なくとも主機能ではない）
- **災害対策**
災害時に友人の状態を確認するニーズが少ない．
家族間以外では災害対策で課金できそうにない．
しかしそれらをターゲットにした待ち合わせアプリは，ニーズが少ないと思われる．
- **広告表示なし**
現状，広告表示なしでGPSをシェアできるアプリは多い．
時間制限を付けるだけでは，課金に至る付加価値にはなりえないと思われる．

待ち合わせアプリは，ユーザへの課金でビジネスモデルを成立させることができないと考えられる．

## 別のプロダクト案
- **ドタキャンされないマッチングアプリ**
実際に会うフェーズになった場合，待ち合わせ時間と待ち合わせ場所を指定する．
待ち合わせ時間付近になると，GPSを共有する or 相手の待ち合わせ場所との距離を表示する．（家ばれ防止）
待ち合わせ時間に待ち合わせ場所にいない場合，ドタキャンと判断し，マイナス評価をする．
ドタキャンをした場合，危険なユーザとして表示される．
面倒になった，近くまで来て顔を見て逃亡するようなケースも抑止できる．
既存サービスがあるかどうかは調べられていない．
会うケースを多く作るような場合に有効であると考えられる．
例）~~[忙しい人のためのマッチングアプリ](https://www.youtube.com/watch?v=uBS4IBD2nTw)~~

**Comment by hirano0709** [comment]
# クリエイターに優しいアプリ
## ソリューションの具体化
基本的には一般的なSNSのようなイメージだが，下記の特徴を持たせる．
- **多元的な指標で評価される**
アートを投稿した際に「いいね」という一元的な指標ではなく，SDGsの17の指標で評価してもらう
例えば，[例](https://prtimes.jp/i/76909/1/resize/d76909-1-579371-7.jpg)は海のごみを用いて作られた作品らしいが，「海の豊かさを守ろう」であったり，「つくる責任 つかう責任」等にフラグを立てるような多元的評価ができるようにする．
それにより，自分のアートがどのような社会的評価を受けているか，「いいね」よりはわかりやすいフィードバックになる．
また，コメント機能を実装したとしても，一定のモラルのある人が登校するようになると考えられるため，誹謗中傷は従来のSNSと比較すると起きにくいと考えられる．
- **コミュニティに属する**
利用者はコミュニティに属し，コミュニティに対して投稿をする．
ホーム画面に表示される作品一覧をフォロワーの作品ではなく，コミュニティの作品にする．
個人のフォロワー数に関係なく，作品が表示できるようになるため，フォロワー数への依存度は少なくなると考えられる．
- **一定以上評価がたまると体験が報酬として与えられる**
例としては，「陸の豊かさも守ろう」の評価がたまれば，リアルな空間に植樹する権利と交換でき，その木を見に行けるみたいな体験とつなげる．
それによって，さらなるアートにつなげられるような仕組みができるといい．

**Comment by usamin24** [comment]
ダイシュクです。

思考整理用アプリ（兼子，宇佐美）
書いていない課題に対するリーンキャンバスの作成
https://docs.google.com/spreadsheets/d/1HkU2nrajIYq7SpEZDYVC7bbx7jDSTWbD4ytrDqvZ8W4/edit?usp=sharing

カフェの混み具合アプリ（宇佐美，今井）
ビジネスモデルの具体化
カフェ側とお客様側のメリットデメリットの抽出

[カフェの混雑状況がわかるアプリ.pdf](https://github.com/kurumu-rika/main/files/9275905/default.pdf)

**Comment by KanekoCadlab** [comment]
宿題
[リーンキャンパス_アプリ製作_カネコ](https://docs.google.com/spreadsheets/d/1bY4amivV_EjASqx2hc1lkxyK5vz-2FEeYHhiYXMmDrQ/edit#gid=1995676988)

**Comment by umatama** [comment]
- 資格のSNS　宇佐美、兼子
 初期のユーザをどう獲得するか
 linkedinとの圧倒的な差別化

- 思考整理用アプリ(汎用的なツール)　宇佐美
 チュートリアル用に作る？
 具体的な画面遷移などのイメージを説明できる感じの資料

- クリエイターに優しいアプリ(SDGs)　兼子、平野、今井
 ビジネスモデル
 費用再検討

- 前回の宿題　今井
 待ち合わせアプリ

**Comment by umatama** [comment]
### 資格のSNS

- [日本の資格　検定](https://jpsk.jp/)
 キーワード検索
 体験談、日記を掲載

- [Brush UP 学び](https://www.brush-up.jp/)
 業界、テーマ別検索
 通信講座も検索可能
 難易度も掲載(指標はざっくり)
