### ISSUE TITLE
洗い出したリスクに対する再調査・深掘り2

### ISSUE THREAD

**Issue by umatama** [kurumu-rika/main#8]
- 資格のSNS　宇佐美、兼子
  - 初期のユーザをどう獲得するか
  - linkedinとの圧倒的な差別化点

- クリエイターに優しいアプリ(SDGs)　兼子、平野、今井
  - ビジネスモデル
  - 費用再検討

- 前回の宿題　今井
  - 待ち合わせアプリ

**Comment by usamin24** [comment]
宿題です。詰んでいるのでいいアイデアがあれば教えていただきたく

＜結論＞
Linkedinとの差別化
→資格に特化した機能の追加を考えたが、類似のWebサービスで良い（アプリである必要性がない）

初期ユーザ
→今資格取得中の場合、受験中のログを残したりやコミュニティを作れてモチベアップというメリットを生み出せるが、
　既にスキルをある程度持っている人（最も教えて欲しい人）が使うメリットがない。（転職に有利、とかはLinkedinで良い）
　資格にかぎらず基本的に教える先輩役のメリットがない。

![Image](https://user-images.githubusercontent.com/97825480/184475398-e9fc8962-6430-4993-a253-944041124a93.png)

**Comment by umatama** [comment]
## クリエイターに優しいアプリ
### ビジネスモデル
- 無料アプリの場合
  - 広告収入の仕組みについて
    - [ブログ収益化の仕組み](https://www.xserver.ne.jp/blog/how-to-monetize-and-popular-ad-services/)
収益を得るためには、広告のクリック、もしくは商品の購入が必要

    - [アプリ収益化の仕組み](https://crowdworks.jp/articles/6956/)
 無料アプリである必要がある
 相場
 100万ダウンロード以上･･･500万円
 10万～50万ダウンロード･･･20万～200万円
 3万～5万ダウンロード･･･5万円

  - その他
  作品への応援料から手数料をもらう
  youtubeのスーパーチャットみたいな

 - 有料アプリの場合
   - 作品を掲載する側が金を払う
   作品を周知できる(自己顕示欲) ⇒ 他の方法がたくさんある
   収益が生まれる ⇒ 新たなビジネスモデルを考える必要がある
   作品の評価がわかる ⇒ 専門家の意見(閲覧者のレベル)、不特定多数の意見(他の方法がたくさんある)
   SDGs指標にしたからといって、収益が生まれるわけではない
   オフライン展示会 ⇒ 労力、コストが大きすぎる

   - 作品を閲覧する側が金を払う
   評価にお金がかかる ⇒ 使うわけない 

### 費用再検討
 - SDGsのロゴ使用方法について ([SDGs ガイドライン](https://www.unic.or.jp/files/SDG_Guidelines_AUG_2019_Final_ja.pdf))
 ⇒商用目的の場合は制約が多い、使用料がかかるかは不明
 ⇒利用申請の受諾難易度が調べられてない

 - オフラインイベント
 [イベント経費](https://imitsu.jp/cost/event-planning/)

**Comment by umatama** [comment]
## 待ち合わせアプリ(まとまってないけど、一旦投稿)
 - 利用者のメリット
 無駄時間の削減･･･多く見積もっても30分？(この時間にいくら払うかと考えると0円)
 ストレス軽減･･･人が到着したら消える
 このアプリ単体で金を払う価値を出すのは難しい

 - 誰なら使うか、どういう状況なら使うか

1.  待ち合わせの頻度が多い人
2.  待ち合わせ人数が多い時の点呼がわり

既存アプリとの差別化
時間、距離を制限してプライバシーの保護

⇒ 1.は既存のアプリでいい

時間、距離の制限自体に価値はない
制限が必要なイベントで、人数管理やサービスの管理があればその管理の補助サービスはビジネスとして有効になりそう

**Comment by umatama** [comment]
## 資格のSNS(メモ程度の案)
 必須共有項目を登録してもらう、ガチガチにフォーマットを定める(リンクトインは記述形式が自由)
 - 資格を取るときに気になること
 受験料、受験日、類似の資格、難易度
 - 案
 受験にあたって購入した書籍や講義の金額など、必要経費を共有(合計金額)
 受験した人が持っていた資格(受講者のレベルがわかる)
 どれ(書籍、講義の種類)をどの程度(時間単位、5段階官能評価)実施したか

**Comment by hirano0709** [comment]
# クリエイターに優しいアプリ
## 費用
### データベース（Firebase）
- ユーザテーブル
    - 1レコード：1kB
    - 10,000ユーザ：10MB（1GBまで無料）
    - データ料：$0.115/GB月×0.01GB=$0.00115/月
    - 書き込み：1回/日×10,000ユーザ=10,000回（20,000回まで無料）
    - 書き込み料：$0.115/100,000回×10,000回=$0.0115/月
    - 読み込み：1回/日×10,000ユーザ=10,000回（50,000回まで無料）
    - 読み込み料：$0.038/100,000回×10,000回=$0.0038/月
- 投稿テーブル
    - 1レコード：100B
    - 10,000ユーザ（1ユーザ100レコード）：100MB（1GBまで無料）
    - データ料：$0.115/GB月×0.1GB=$0.0115/月
    - 書き込み：1回/日×10,000ユーザ=10,000回（20,000回まで無料）
    - 書き込み料：$0.115/100,000回×10,000回=$0.0115/月
    - 読み込み：1,000回/日×10,000ユーザ=10,000,000回（50,000回まで無料）
    - 読み込み料：$0.038/100,000回×10,000,000回=$3.8/月

### 画像ストレージ（Google Cloud Storage）
- 投稿画像
    - 1画像：10MB（だいたい4K）
    - 10,000ユーザ（1ユーザ100投稿）：10MB×100×10,000=10TB
    - データ料：$0.023/GB月×10TB=$230/月

## ビジネスモデル
- アートの所有権の売買に対して，維持費に必要なくらいの手数料をもらう．
- アートの所有権の売買の一部を，コミュニティの活動費に充てる．
- オンライン展示会の一部を，コミュニティの活動費に充てる．

**Comment by KanekoCadlab** [comment]
### 資格のSNS

＜結論＞
ダメそう。

先輩役のメリットを考える
そのために、市場調査。
→インスタで投稿数が多かったのは、勉強ノートの公開
ノートを公開する理由
誰かの憧れになりたい
勉強仲間意識
勉強垢なんてものがある
→高校生が大学受験の勉強日記のようなもの。
資格の投稿についても調べたが、まったくいいね/フォロワーを稼げていなかった。
（いいねが多かったのはお金関連、美容関連？の投稿だけ）
→先輩役にはamazonギフト券か？　ランキング機能つけるとか？
称賛
自分が紹介する立場でも投稿しようと思うものは何か、、？
モチベは誇示、自己満なのでは？それをうまく利用するには？

初期ユーザとして、インスタで投稿しているインフルエンサーを取り込むことを想定していたが、
強力なインフルエンサーがいない。。という結果に終わった。

投稿をみる側のメリット
どんな学習本を使っていたか知ることができる


### クリエイターに優しいアプリ(SDGs)

actcoin強そう
[actcoin](https://actcoin.jp/)

ポイントを寄付する

slowz
サステナブルな活動をしているお店をマップ上に紹介する
採算がとれなかったのか、1年前のリリースから更新なし

ごみ拾いアプリやフードロス対策など特化したサービスはある。

環境省のアプリ
[COOL CHOICE](https://ondankataisaku.env.go.jp/coolchoice/index.html#sec02)
SDGsの事例紹介
知名度はそんなになさそう
